package sw.environment;

public enum RoomUpdateType
{
    ACCEPT_REQUEST,
    ASK,
    CREATURE_ADDED, 
    CREATURE_REMOVED, 
    CREATURE_RESOURCE_ADDED, 
    CREATURE_RESOURCE_REMOVED,
    EXIT_ADDED,
    ERROR_MSG,
    FAILED_ACCEPT_REQUEST,
    FAILED_JOIN_REQUEST,
    FAILED_LEAVE_REQUEST,
    GET_ITEM,
    ITEM_ADDED,
    ITEM_DROPPED,
    ITEM_REMOVED,
    JOIN_REQUEST,
    LEAVE_REQUEST,
    MOVE,
    MOVE_FAILED,
    NPC_ADDED, 
    NPC_REMOVED,
    PLAYER_ADDED, 
    PLAYER_REMOVED,
    SAID,
    WEAR_ITEM
}
