package sw.environment;

public enum SWRoomUpdateType
{
    CREATURE_ADDED, CREATURE_REMOVED, NPC_ADDED, NPC_REMOVED, PLAYER_ADDED, PLAYER_REMOVED, EXIT_ADDED,
    ITEM_ADDED, ITEM_REMOVED, CREATURE_RESOURCE_ADDED, CREATURE_RESOURCE_REMOVED

}
