package sw.socialNetwork.simulation;

/**
 * @author David Abrams
 *
 * These are the different types of events generated to pass data up to the Simulation.
 */
public enum EventTypes 
{
	FRIEND_REQUEST_SENT,
	FRIEND_REQUEST_RECIEVED,
	FRIEND_REQUEST_ACCEPTED,
	FRIEND_REQUEST_REJECTED,
	QUEST_CREATED_GIFTQUEST,
	QUEST_CREATED_FAVORQUEST,
	QUEST_CREATED_REQFAVQUEST,
	QUEST_CREATED_HOMEWRECKER,
	QUEST_SUCCESSFUL,
	QUEST_FAILED,
	FRIENDSHIP_CREATED,
	FRIENDSHIP_TERMINATED,
	CAPITAL_CHANGED,
	MOOD_CHANGE_TO_HAPPY,
	MOOD_CHANGE_TO_ANGRY;
}